import { BadRequestException, Injectable } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { requireEnv } from '../common/index.js';
import { Strategy, type Profile } from 'passport-google-oauth20';
import { verifyLinkState } from './oauth-link-state.js';

/** Maximum age of the OAuth link state token before it is rejected. */
const FIVE_MINUTES_MS = 5 * 60 * 1000;

/**
 * Passport strategy for Google account-linking (as opposed to sign-in).
 * Registered under the name `'google-link'` and used exclusively by
 * `GET /auth/google/link/callback`.
 *
 * Unlike the sign-in strategy, this strategy verifies a signed HMAC
 * `state` parameter (generated by `generateLinkState`) to confirm that
 * the OAuth callback belongs to an authenticated Linklater user and that
 * the flow was initiated within the last 5 minutes.
 *
 * NOTE: `state: false` is intentional - we manage state manually via HMAC
 * rather than relying on passport-google-oauth20's built-in state handling,
 * which would require a session store.
 */
@Injectable()
export class GoogleLinkStrategy extends PassportStrategy(
  Strategy,
  'google-link',
) {
  constructor() {
    super({
      clientID: requireEnv('GOOGLE_CLIENT_ID'),
      clientSecret: requireEnv('GOOGLE_CLIENT_SECRET'),
      callbackURL: requireEnv('GOOGLE_LINK_CALLBACK_URL'),
      scope: ['email', 'profile'],
      passReqToCallback: true,
      state: false,
    });
  }

  /**
   * Called by Passport after Google completes the OAuth flow. Verifies the
   * HMAC state, extracts the Linklater user ID from it, and returns the
   * Google profile data needed by the controller to link the account.
   *
   * @param request - The incoming HTTP request (used to read `query.state`).
   * @param _accessToken - Google access token (unused - we only need the profile).
   * @param _refreshToken - Google refresh token (unused).
   * @param profile - The Google OAuth profile.
   * @returns `{ userId, providerId, providerEmail }` attached to `request.user`.
   * @throws {BadRequestException} When the state is missing, tampered, or expired.
   */
  async validate(
    request: { query?: { state?: string } },
    _accessToken: string,
    _refreshToken: string,
    profile: Profile,
  ) {
    const state = request.query?.state ?? '';
    const userId = verifyLinkState(
      state,
      requireEnv('JWT_SECRET'),
      FIVE_MINUTES_MS,
    );
    if (!userId) {
      throw new BadRequestException('Invalid or expired link state');
    }

    const providerEmail = profile.emails?.[0]?.value ?? '';
    return { userId, providerId: profile.id, providerEmail };
  }
}
