import { ApiProperty } from '@nestjs/swagger';
import { IsString, MinLength } from 'class-validator';

/**
 * Request body for `POST /auth/extension/token`. Completes the PKCE
 * authorization code exchange started by `GET /auth/extension/authorize`.
 *
 * The server re-derives the `code_challenge` (SHA-256 of `codeVerifier`,
 * base64url-encoded) and compares it to the value stored when the code was
 * issued. A mismatch results in `401 Unauthorized`.
 */
export class ExtensionTokenDto {
  @ApiProperty({
    description:
      'The raw authorization code received as the `code` query parameter' +
      ' in the redirect from `GET /auth/extension/authorize`.',
    example: 'a3f8c...64-character-hex-string...d91e',
  })
  @IsString()
  @MinLength(1)
  code: string;

  @ApiProperty({
    description:
      'The original PKCE code verifier generated by the extension before' +
      ' the authorization request. The server derives the challenge from' +
      ' this value and compares it to the stored challenge.',
    example: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
  })
  @IsString()
  @MinLength(1)
  codeVerifier: string;
}
