listen_addresses = '*'
effective_cache_size = 2GB
maintenance_work_mem = 128MB
max_connections = 50
max_parallel_workers = 4
max_parallel_workers_per_gather = 2
max_worker_processes = 4
random_page_cost = 1.1
shared_buffers = 1GB
work_mem = 8MB
